package org.opensrp.domain.postgres;

import java.util.Date;

public class Event {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * core.event.id
	 * 
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	private Long id;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * core.event.json
	 * 
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	private Object json;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * core.event.date_deleted
	 * 
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	private Date dateDeleted;
	
	private String providerId;
	
	private String eventType;
	
	private Long serverVersion;
	
	private String baseEntityId;
	
	private String district;
	
	private String division;
	
	private String branch;
	
	private String village;
	
	private String formSubmissionId;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column core.event.id
	 * 
	 * @return the value of core.event.id
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	public Long getId() {
		return id;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column core.event.id
	 * 
	 * @param id the value for core.event.id
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column core.event.json
	 * 
	 * @return the value of core.event.json
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	public Object getJson() {
		return json;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column core.event.json
	 * 
	 * @param json the value for core.event.json
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	public void setJson(Object json) {
		this.json = json;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column core.event.date_deleted
	 * 
	 * @return the value of core.event.date_deleted
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	public Date getDateDeleted() {
		return dateDeleted;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column core.event.date_deleted
	 * 
	 * @param dateDeleted the value for core.event.date_deleted
	 * @mbg.generated Fri Apr 06 16:01:06 EAT 2018
	 */
	public void setDateDeleted(Date dateDeleted) {
		this.dateDeleted = dateDeleted;
	}
	
	public String getProviderId() {
		return providerId;
	}
	
	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}
	
	public String getEventType() {
		return eventType;
	}
	
	public void setEventType(String eventType) {
		this.eventType = eventType;
	}
	
	public Long getServerVersion() {
		return serverVersion;
	}
	
	public void setServerVersion(Long serverVersion) {
		this.serverVersion = serverVersion;
	}
	
	public String getBaseEntityId() {
		return baseEntityId;
	}
	
	public void setBaseEntityId(String baseEntityId) {
		this.baseEntityId = baseEntityId;
	}
	
	public String getDistrict() {
		return district;
	}
	
	public void setDistrict(String district) {
		this.district = district;
	}
	
	public String getBranch() {
		return branch;
	}
	
	public void setBranch(String branch) {
		this.branch = branch;
	}
	
	public String getVillage() {
		return village;
	}
	
	public void setVillage(String village) {
		this.village = village;
	}
	
	public String getDivision() {
		return division;
	}
	
	public void setDivision(String division) {
		this.division = division;
	}
	
}
